#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure_ac
# autospec version: v4
# autospec commit: f4bef72a70f8
#
Name     : dymo-cups-drivers
Version  : 1.4.0
Release  : 1
URL      : https://download.dymo.com/dymo/Software/Download%20Drivers/Linux/Download/dymo-cups-drivers-1.4.0.tar.gz
Source0  : https://download.dymo.com/dymo/Software/Download%20Drivers/Linux/Download/dymo-cups-drivers-1.4.0.tar.gz
Summary  : DYMO LabelWriter Drivers for CUPS
Group    : Development/Tools
License  : GPL-2.0
Requires: dymo-cups-drivers-data = %{version}-%{release}
Requires: dymo-cups-drivers-license = %{version}-%{release}
BuildRequires : cups-dev
BuildRequires : pkgconfig(cppunit)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Inheritate-CXXFLAGS-from-the-environment-to-use-dpkg.patch
Patch2: 0002-Port-to-newer-cups-headers-ppd_file_t-is-only-define.patch
Patch3: 0003-Don-t-fail-the-ppd-test-if-the-cups-filters-is-not-a.patch
Patch4: 0005-Include-cups-sidechannel.h-for-cupsBackChannelRead-s.patch
Patch5: 0006-Backport-Replaced-boolean-OR-by-bitwise-OR-fix.patch
Patch6: 0007-Backport-Replaced-deprecated-type-std-auto_ptr-by-st.patch
Patch7: 0008-Backport-Add-missing-backend-header.patch
Patch8: 0009-gcc11-ftbfs-replace-byte-by-unsigned-char.patch
Patch9: 0010-deactivate-tests-due-to-gcc12.patch

%description
DYMO LabelWriter and DYMO LabelMANAGER series drivers for CUPS

%package data
Summary: data components for the dymo-cups-drivers package.
Group: Data

%description data
data components for the dymo-cups-drivers package.


%package license
Summary: license components for the dymo-cups-drivers package.
Group: Default

%description license
license components for the dymo-cups-drivers package.


%prep
%setup -q -n dymo-cups-drivers-1.4.0.5
cd %{_builddir}/dymo-cups-drivers-1.4.0.5
%patch -P 1 -p1
%patch -P 2 -p1
%patch -P 3 -p1
%patch -P 4 -p1
%patch -P 5 -p1
%patch -P 6 -p1
%patch -P 7 -p1
%patch -P 8 -p1
%patch -P 9 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1711138514
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1711138514
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/dymo-cups-drivers
cp %{_builddir}/dymo-cups-drivers-%{version}.5/COPYING %{buildroot}/usr/share/package-licenses/dymo-cups-drivers/55d6c320ee38d8193d4ffba8dadeb13a6f01eda6 || :
cp %{_builddir}/dymo-cups-drivers-%{version}.5/LICENSE %{buildroot}/usr/share/package-licenses/dymo-cups-drivers/06877624ea5c77efe3b7e39b0f909eda6e25a4ec || :
export GOAMD64=v2
GOAMD64=v2
%make_install

%files
%defattr(-,root,root,-)
/usr/lib/cups/filter/raster2dymolm
/usr/lib/cups/filter/raster2dymolw

%files data
%defattr(-,root,root,-)
/usr/share/cups/model/lm400.ppd
/usr/share/cups/model/lm450.ppd
/usr/share/cups/model/lmpc.ppd
/usr/share/cups/model/lmpc2.ppd
/usr/share/cups/model/lmpnp.ppd
/usr/share/cups/model/lp350.ppd
/usr/share/cups/model/lw300.ppd
/usr/share/cups/model/lw310.ppd
/usr/share/cups/model/lw315.ppd
/usr/share/cups/model/lw320.ppd
/usr/share/cups/model/lw330.ppd
/usr/share/cups/model/lw330t.ppd
/usr/share/cups/model/lw400.ppd
/usr/share/cups/model/lw400t.ppd
/usr/share/cups/model/lw450.ppd
/usr/share/cups/model/lw450dl.ppd
/usr/share/cups/model/lw450dt.ppd
/usr/share/cups/model/lw450t.ppd
/usr/share/cups/model/lw450tt.ppd
/usr/share/cups/model/lw4xl.ppd
/usr/share/cups/model/lwduol.ppd
/usr/share/cups/model/lwduot.ppd
/usr/share/cups/model/lwduot2.ppd
/usr/share/cups/model/lwtt.ppd
/usr/share/cups/model/se450.ppd

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/dymo-cups-drivers/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
/usr/share/package-licenses/dymo-cups-drivers/55d6c320ee38d8193d4ffba8dadeb13a6f01eda6
